[build]
  command = "npm run build"
  publish = "dist"

[build.environment]
  NODE_ENV = "production"

# Environment variables
[context.production.environment]
  VITE_API_BASE_URL = "https://mern-blog-backend-2efn.onrender.com"

[context.deploy-preview.environment]
  VITE_API_BASE_URL = "https://mern-blog-backend-2efn.onrender.com"

[context.branch-deploy.environment]
  VITE_API_BASE_URL = "https://mern-blog-backend-2efn.onrender.com"
